version: '3.8'

networks:
  mesh-hub-net:
    driver: bridge

name: mesh-hub

services:
  postgres:
    image: postgres:14-alpine
    container_name: db
    env_file: ./server/.env
    networks:
      - mesh-hub-net
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "8888:5432"
    restart: unless-stopped

volumes:
  db:
    name: mesh-hub-db-volume
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./data/db"
