server {
  listen 80 default_server;
  listen [::]:80 default_server;
  
  gzip on;
  gzip_types text/plain application/xml text/css application/javascript;
  gzip_min_length 1000;
  
  client_max_body_size 0;

  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri /index.html;
  }

  location /api/ {
    proxy_redirect off;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 1m;
    proxy_connect_timeout 1m;
    proxy_pass http://api:8080;
  }
}

# server {
#   listen 443 ssl;
#   server_name mesh-hub.ru;
#
#   client_max_body_size 500M;
#
#   ssl_certificate /etc/nginx/ssl/certificate.crt;
#   ssl_certificate_key /etc/nginx/ssl/private-key.key;
#
#   ssl_certificate /etc/letsencrypt/live/kampus-dev-next.softmedialab.com/fullchain.pem; # managed by Certbot
#   ssl_certificate_key /etc/letsencrypt/live/kampus-dev-next.softmedialab.com/privkey.pem; # managed by Certbot
#   include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
#   ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
#
#   resolver 127.0.0.11 valid=10s ipv6=off;
#   set $backend_server host.docker.internal;
#
#   location / {
#     root /usr/share/nginx/html;
#     index index.html index.htm;
#     try_files $uri /index.html;
#   }
#
#   location /api/ {
#     client_max_body_size 1024M;
#     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#     proxy_set_header Host $host;
#
#     proxy_http_version 1.1;
#     proxy_set_header Upgrade $http_upgrade;
#     proxy_set_header Connection "upgrade";
#     proxy_pass http://$backend_server:8080;
#   }
#
#   location /swagger/ {
#     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#     proxy_set_header Host $host;
#
#     proxy_http_version 1.1;
#     proxy_set_header Upgrade $http_upgrade;
#     proxy_set_header Connection "upgrade";
#     proxy_pass http://$backend_server:8080;
#   }
# }
