# Server Configuration
server {
  listen 80 default_server;
  listen [::]:80 default_server;

  server_name mesh-hub.ru;

  # Gzip Compression
  gzip on;
  gzip_types text/plain application/xml text/css application/javascript;
  gzip_proxied no-cache no-store private expired;
  gzip_min_length 1000;

  # Client Configuration
  client_max_body_size 512M;

  # Static File Serving
  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri /index.html;
  }

  # Proxy Configuration
  location ~ ^/(api|swagger)/ {
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://api:8080;
  }

  # location /swagger/ {
  #   proxy_http_version 1.1;
  #   proxy_set_header Host $host;
  #   proxy_set_header X-Real-IP $remote_addr;
  #   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  #   proxy_set_header X-Forwarded-Host $host;
  #   proxy_set_header X-Forwarded-Proto $scheme;
  #   proxy_pass http://api:8080;
  # }
}
